mode = "debug"
address = ":3306"
sessionsecret = "nayim"
[database]
username = "dbo618511085"
password = "fibrimad"
database = "db618511085.db.1and1.com"
[roles]
Administrador = [
    "login",
    "create_user",
    "user_list",
    "edit_user",
    "view_user",
    "remove_user",
    "delete_user",
    "create_work_order",
    "work_order_list",
    "edit_work_order",
    "delete_work_order",
    "upload_file_work_order",
    "view_work_order",
    "view_file",
    "delete_file",
    "edit_file",
    "create_box",
    "view_box",
    "edit_box",
    "delete_box",
    "view_file_box",
    "upload_file_box"
]
Usuario = [
    "login"
]
